services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb+srv://dbAdmin:AdminSavory123@cluster0.4nqhgbl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    volumes:
      - .:/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: